export const TOGGLE_GAME_POWER = 'TOGGLE_GAME_POWER';
export type TOGGLE_GAME_POWER = typeof TOGGLE_GAME_POWER;

export const START_GAME = 'START_GAME';
export type START_GAME = typeof START_GAME;

export const START_NEXT_ROUND = 'START_NEXT_ROUND';
export type START_NEXT_ROUND = typeof START_NEXT_ROUND;

export const ROUND_SUCCESS = 'ROUND_SUCCESS';
export type ROUND_SUCCESS = typeof ROUND_SUCCESS;

export const SET_LIGHT_SEQUENCE = 'SET_LIGHT_SEQUENCE';
export type SET_LIGHT_SEQUENCE = typeof SET_LIGHT_SEQUENCE;
